backend:
  name: github
  repo: subhashdissanayaka-byte/valtivra
  branch: main
  client_id: 1e1270610465cf8e77dad7342838f7e8dcb6bc2d
  base_url: https://decap-cms-oauth.netlify.app

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog Articles"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Investing", "Personal Finance", "Markets", "Crypto"] }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Body Content", name: "body", widget: "markdown" }
